spring:
  application:
    name: UserManagementApp
  jpa:
    #    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: '12345'
    url: jdbc:mysql://localhost:3306/user_management_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=LOCAL

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080